name = "cloudflare"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[ d1_databases ]]
binding = "DB"
database_name = "cloudflare"
database_id = "bd0ee562-d2c7-4445-90b6-2b69d66021c3"